# Generated by Django 4.0.5 on 2022-07-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

# instead of create model django is going the product table and renaming 
# the price column to unit_price
    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
