# Generated by Django 4.0.5 on 2022-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
